[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[1000]
type=endpoint
context=interno
disallow=all
allow=ulaw
auth=1000
aors=1000

[1000]
type=auth
auth_type=userpass
password=1234
username=1000

[1000]
type=aor
max_contacts=1

[1001]
type=endpoint
context=interno
disallow=all
allow=ulaw
auth=1001
aors=1001

[1001]
type=auth
auth_type=userpass
password=1234
username=1001

[1001]
type=aor
max_contacts=1